export const englishgrammarData = [
  { id: 'e_row1', kram: '1.', title: 'Using the Dictionary', status: 'pending' },
  { id: 'e_row2', kram: '2.', title: 'The Sentence', status: 'pending' },
  { id: 'e_row3', kram: '3.', title: 'Subject and Predicate', status: 'pending' },
  { id: 'e_row4', kram: '4.', title: 'Parts of Speech', status: 'pending' },
  { id: 'e_row5', kram: '5.', title: 'Nouns', status: 'pending' },
  { id: 'e_row6', kram: '6.', title: 'The Noun: Number (Singular and Plural)', status: 'pending' },
  { id: 'e_row7', kram: '7.', title: 'The Noun: Gender', status: 'pending' },
  { id: 'e_row8', kram: '8.', title: 'Nouns - Possessive Case', status: 'pending' },
  { id: 'e_row9', kram: '9.', title: 'Adjectives', status: 'pending' },
  { id: 'e_row10', kram: '10.', title: "Articles ('A', 'An' and 'The')", status: 'pending' },
  { id: 'e_row11', kram: '11.', title: 'Pronouns', status: 'pending' },
  { id: 'e_row12', kram: '★', title: 'Revision Exercises I (Chapters 1 to 11)', status: 'pending', isSpecial: true },
  { id: 'e_row13', kram: '12.', title: 'The Verb - Kinds of Verbs', status: 'pending' },
  { id: 'e_row14', kram: '13.', title: 'Forms of Verbs', status: 'pending' },
  { id: 'e_row15', kram: '14.', title: 'Tenses: Form and Use (Simple Present and Simple Past)', status: 'pending' },
  { id: 'e_row16', kram: '15.', title: 'Present Continuous Tense and Past Continuous Tense', status: 'pending' },
  { id: 'e_row17', kram: '16.', title: 'Simple Future Tense and Future Continuous Tense', status: 'pending' },
  { id: 'e_row18', kram: '17.', title: 'Present Perfect Tense, Past Perfect Tense and Future Perfect Tense', status: 'pending' },
  { id: 'e_row19', kram: '18.', title: 'Present Perfect Continuous, Past Perfect Continuous and Future Perfect Continuous Tense', status: 'pending' },
  { id: 'e_row20', kram: '19.', title: 'Agreement of the Verb with the Subject', status: 'pending' },
  { id: 'e_row21', kram: '20.', title: 'Active and Passive Voice', status: 'pending' },
  { id: 'e_row22', kram: '★', title: 'Revision Exercises II (Chapters 12 to 20)', status: 'pending', isSpecial: true },
  { id: 'e_row23', kram: '21.', title: 'Adverbs', status: 'pending' },
  { id: 'e_row24', kram: '22.', title: 'Prepositions', status: 'pending' },
  { id: 'e_row25', kram: '23.', title: 'Conjunctions', status: 'pending' },
  { id: 'e_row26', kram: '24.', title: 'Punctuation and Capital Letters', status: 'pending' },
  { id: 'e_row27', kram: '25.', title: 'Direct and Indirect Speech: Reported Speech', status: 'pending' },
  { id: 'e_row28', kram: '★', title: 'Revision Exercises III (Chapters 21 to 25)', status: 'pending', isSpecial: true },
  { id: 'e_row29', kram: '26.', title: 'Short Composition (Comprehension Passages)', status: 'pending' },
  { id: 'e_row30', kram: '27.', title: 'Picture Description and Story Writing', status: 'pending' },
  { id: 'e_row31', kram: '28.', title: 'Letter Writing', status: 'pending' },
  { id: 'e_row32', kram: '29.', title: 'Paragraph Writing/Essay Writing', status: 'pending' },
  { id: 'e_row33', kram: '30.', title: 'Short Composition (Message Writing - Notice Writing - Slogan Writing)', status: 'pending' },
  { id: 'e_row34', kram: '★', title: 'Revision Test Paper', status: 'pending', isSpecial: true },
  { id: 'e_row35', kram: '★', title: 'Test Paper', status: 'pending', isSpecial: true },
];
