export const hindiData = [
  { id: 'h_row1', kram: '1.', title: 'यातायात (चित्रपाठ)', type: '-', page: '01', status: 'pending' },
  { id: 'h_row2', kram: '2.', title: 'गिनती (२१ से ५०)', type: '-', page: '09', status: 'pending' },
  { id: 'h_row3', kram: '3.', title: 'नन्हा मुन्ना राही हूँ', type: 'कविता', page: '14', status: 'pending' },
  { id: 'h_row4', kram: '4.', title: 'सोच अपनी-अपनी', type: '-', page: '20', status: 'pending' },
  { id: 'h_row5', kram: '■', title: 'पुनरावर्तन : 1', type: '-', page: '25', status: 'pending', isSpecial: true },
  { id: 'h_row6', kram: '5.', title: 'चिड़ियाघर की सैर', type: '-', page: '28', status: 'pending' },
  { id: 'h_row7', kram: '6.', title: 'हँसी का पिटारा', type: 'चुटकुले', page: '35', status: 'pending' },
  { id: 'h_row8', kram: '7.', title: 'खाना खज़ाना (चित्रपाठ)', type: '-', page: '38', status: 'pending' },
  { id: 'h_row9', kram: '8.', title: 'भरत मिलाप', type: 'एकांकी', page: '44', status: 'pending' },
  { id: 'h_row10', kram: '■', title: 'पुनरावर्तन : 2', type: '-', page: '53', status: 'pending', isSpecial: true },
  { id: 'h_row11', kram: '■', title: 'कसौटी', type: '-', page: '57', status: 'pending', isSpecial: true },
  { id: 'h_row12', kram: '9.', title: 'कैसा शोर ?', type: 'चित्र-कथा', page: '62', status: 'pending' },
  { id: 'h_row13', kram: '10.', title: 'सीखो', type: 'कविता', page: '70', status: 'pending' },
  { id: 'h_row14', kram: '11.', title: 'सच्चा बालक', type: 'जीवन-प्रसंग', page: '75', status: 'pending' },
  { id: 'h_row15', kram: '12.', title: 'दुमदुमा गाँव के बच्चे', type: 'कहानी', page: '80', status: 'pending' },
  { id: 'h_row16', kram: '■', title: 'पुनरावर्तन : 3', type: '-', page: '88', status: 'pending', isSpecial: true },
  { id: 'h_row17', kram: '13.', title: 'स्वच्छता', type: 'निबंध', page: '91', status: 'pending' },
  { id: 'h_row18', kram: '14.', title: 'हम भारत की शान हैं !', type: 'कविता', page: '97', status: 'pending' },
  { id: 'h_row19', kram: '15.', title: 'खरगोश और हाथी', type: 'चित्र-कथा', page: '100', status: 'pending' },
  { id: 'h_row20', kram: '16.', title: 'पहेलियाँ', type: 'पहेलियाँ', page: '106', status: 'pending' },
  { id: 'h_row21', kram: '■', title: 'पुनरावर्तन : 4', type: '-', page: '109', status: 'pending', isSpecial: true },
];
